// Role Permissions Matrix
export const ROLE_PERMISSIONS = {
  master_admin: {
    users: ['create', 'read', 'update', 'delete', 'manage_roles'],
    roles: ['create', 'read', 'update', 'delete'],
    leads: ['create', 'read', 'update', 'delete', 'assign', 'export', 'bulk'],
    customers: ['create', 'read', 'update', 'delete', 'export', 'bulk'],
    deals: ['create', 'read', 'update', 'delete', 'assign', 'export'],
    deposits: ['create', 'read', 'update', 'delete', 'approve', 'export'],
    tasks: ['create', 'read', 'update', 'delete', 'assign'],
    staff: ['create', 'read', 'update', 'delete', 'view_stats'],
    dashboard: ['view_all', 'view_kpi', 'view_reports'],
    settings: ['read', 'update'],
    audit: ['read', 'export'],
    notifications: ['read', 'manage'],
    files: ['create', 'read', 'delete'],
  },
  admin: {
    users: ['create', 'read', 'update'],
    roles: ['read'],
    leads: ['create', 'read', 'update', 'delete', 'assign', 'export', 'bulk'],
    customers: ['create', 'read', 'update', 'delete', 'export'],
    deals: ['create', 'read', 'update', 'delete', 'assign', 'export'],
    deposits: ['create', 'read', 'update', 'approve', 'export'],
    tasks: ['create', 'read', 'update', 'delete', 'assign'],
    staff: ['read', 'update', 'view_stats'],
    dashboard: ['view_all', 'view_kpi'],
    settings: ['read'],
    audit: ['read'],
    notifications: ['read', 'manage'],
    files: ['create', 'read', 'delete'],
  },
  manager: {
    users: [],
    roles: [],
    leads: ['create', 'read', 'update'],
    customers: ['create', 'read', 'update'],
    deals: ['create', 'read', 'update'],
    deposits: ['read'],
    tasks: ['create', 'read', 'update'],
    staff: [],
    dashboard: ['view_own'],
    settings: [],
    audit: [],
    notifications: ['read'],
    files: ['create', 'read'],
  },
  finance: {
    users: ['read'],
    roles: [],
    leads: ['read'],
    customers: ['read'],
    deals: ['read', 'export'],
    deposits: ['create', 'read', 'update', 'approve', 'export'],
    tasks: ['read'],
    staff: ['read'],
    dashboard: ['view_finance'],
    settings: [],
    audit: ['read'],
    notifications: ['read'],
    files: ['create', 'read'],
  },
};

// Default status transitions
export const LEAD_STATUS_TRANSITIONS = {
  new: ['contacted', 'qualified', 'lost', 'archived'],
  contacted: ['qualified', 'proposal', 'lost', 'archived'],
  qualified: ['proposal', 'negotiation', 'lost', 'archived'],
  proposal: ['negotiation', 'won', 'lost', 'archived'],
  negotiation: ['won', 'lost', 'archived'],
  won: ['archived'],
  lost: ['new', 'archived'],
  archived: ['new'],
};

export const DEAL_STATUS_TRANSITIONS = {
  draft: ['pending', 'cancelled'],
  pending: ['in_progress', 'cancelled'],
  in_progress: ['awaiting_payment', 'cancelled'],
  awaiting_payment: ['paid', 'cancelled'],
  paid: ['completed', 'cancelled'],
  completed: [],
  cancelled: ['draft'],
};

export const DEPOSIT_STATUS_TRANSITIONS = {
  pending: ['confirmed', 'failed'],
  confirmed: ['processing', 'refunded'],
  processing: ['completed', 'refunded'],
  completed: ['refunded'],
  refunded: [],
  failed: ['pending'],
};
